### ISSUE TITLE
Issue with submission. 

### ISSUE THREAD

**Issue by Gchism94** [INFO-523-Exercises/hw-03-riyanshibohra#1]
Hi riyanshibohra, 

I cannot reproduce your submission because you used a local path to read in the data. Please replace these paths with the absolute path in the repo. I suggest using the `here()` package. See [Project Relative Paths](https://cran.r-project.org/web/packages/here/vignettes/here.html)

**Comment by riyanshibohra** [comment]
I have made changes to my submission and changed the path to :spam <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-15/spam.csv')

**Comment by riyanshibohra** [comment]
I have made changes to my submission and changed the path to:                                                                                              
spam <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-08-15/spam.csv'). Hope this makes rendering possible.
